### PR TITLE
fix: drag and drop nodes not working

### LINKED ISSUE #1: Drag and Drop From Folder to Folder not working - Crashes application

### PR DESCRIPTION
**Pull request by ikeohachidi**
fixes #1

### CODE REVIEW

File: src/businessLogic/treviewViewModel/treeViewViewModel.ts [hunk 1]
```diff
@@ -105,6 +106,10 @@ export const TreeViewViewModel: TreeViewViewModel = {
         if(!TreeViewItem.parentId) return;
 
         const parent = flattenedNodesLookUp[TreeViewItem.parentId]
-        parent.children?.push(TreeViewItem);
+        if (parent.children) {
+            parent.children.push(TreeViewItem);
+        } else {
+            Vue.set(parent, 'children', [TreeViewItem])
```
Comment (geekhybrid) [inline src/businessLogic/treviewViewModel/treeViewViewModel.ts]: Is there a way to build the ViewModel to be agnostic of Vue ?

**Review by geekhybrid — APPROVED** [review]
